baseURL = "http://learn.iver.mx/"
languageCode = "en-us"
title = "Aprendiendo a usar SASS con hugo"
disableKinds = ["sitemap", "RSS"]
theme = "hugo-webslides"

tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "Iver"
  homepage = "https://iver.mx"


[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
